# ================================================
#  CONEXION A MySQL - La base de datos se crea automaticamente
# ================================================
spring.datasource.url=jdbc:mysql://root:vcAOwopvSmBEcnngbuQxBjokpJCItDHy@centerbeam.proxy.rlwy.net:31202/railway
spring.datasource.username=root
spring.datasource.password=vcAOwopvSmBEcnngbuQxBjokpJCItDHy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================================================
#  JPA / Hibernate - Crea y actualiza tablas automaticamente
# ================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================================
#  Servidor
# ================================================
server.port=8081
logging.pattern.dateformat=HH:mm
server.error.include-message=always
